# User-agent used for querying Wikidata API
CUSTOM_UA: "spd (cloud-vps) -- isaac@wikimedia.org"

DEBUG: False
LOG_LEVEL: WARNING

ENABLE_UI: False

EARLIEST_TS: 'YYYY-MM-DDTHH:MM:SSZ'
MOST_RECENT_REV_TS: 'YYYY-MM-DDTHH:MM:SSZ'

TEMPORAL_OFFSET: '<tuple of -k through k hour offset -- e.g., (-1, 0, 1)>'
NAMESPACES: '<list of relevant namespace numbers -- e.g., [0] for just main namespace>'
EDIT_WINDOW: 'maximum # of edits between two editors to be considered overlap'

BASIC_AUTH_USERNAME: '<USERNAME>'
BASIC_AUTH_PASSWORD: '<PASSWORD>'
