# User-agent used for querying Wikidata API
CUSTOM_UA: "Wikimedia similar-users service"

DEBUG: False
LOG_LEVEL: DEBUG

ENABLE_UI: False

# An RFC1738 uri used to connect to a database.
# The naming convention is enforced by the Flask-SQLAlchemy module.
# See https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/
SQLALCHEMY_DATABASE_URI: 'sqlite:///:memory:'
SQLALCHEMY_TRACK_MODIFICATIONS: False

EARLIEST_TS: '2020-01-01T00:00:00Z'
MOST_RECENT_REV_TS: '2020-09-30T23:59:59Z'

TEMPORAL_OFFSET: '(-1, 0, 1)'
NAMESPACES: [0, 1, 118]
EDIT_WINDOW: 5

BASIC_AUTH_USERNAME: 'changeme'
BASIC_AUTH_PASSWORD: 'changemepls'
